image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Compile self" # runs during prebuild
    init: |
      for _image in archlinux centos debian fedora "opensuse/leap" ubuntu "voidlinux/voidlinux"; do
        docker pull $_image;
      done
      bashbox build --release
  - name: Arch
    command: docker run --name archlinux -it archlinux bash -c 'pacman -Sy; exec $0 -l'
  - name: CentOS
    command: docker run --name centos -it centos bash -c 'dnf check-update; exec $0 -l'
  - name: Debian
    command: docker run --name debian -it debian bash -c 'apt-get update; exec $0 -l'
  - name: Fedora
    command: docker run --name fedora -it fedora bash -c 'dnf check-update; exec $0 -l'
  - name: Opensuse
    command: docker run --name opensuse_leap -it opensuse/leap bash -c 'zypper refresh; exec $0 -l'
  - name: Ubuntu
    command: docker run --name ubuntu -it ubuntu bash -c 'apt-get update; exec $0 -l'
  - name: Void
    command: docker run --name voidlinux_voidlinux -it voidlinux/voidlinux sh -c 'xbps-install -Sy; exec $0 -l'

vscode:
  extensions:
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
