image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Compile self" # runs during prebuild
    init: "clear && bashbox build --release"

vscode:
  extensions:
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
