#!/data/data/com.termux/files/usr/bin/env bash
main@bashbox%6559 () 
{ 
    function process::self::exit () 
    { 
        local _r=$?;
        kill -USR1 "$___self_PID";
        exit $_r
    };
    function process::self::forcekill () 
    { 
        exec 2> /dev/null;
        kill -9 "$___self_PID"
    };
    function log::error () 
    { 
        local _retcode="${2:-$?}";
        local _exception_line="$1";
        local _source="${BB_ERR_SOURCE:-"${BASH_SOURCE[-1]}"}";
        if [[ ! "$_exception_line" == "("*")" ]]; then
            { 
                echo -e "[!!!] \033[1;31merror\033[0m[$_retcode]: ${_source##*/}[$BASH_LINENO]: ${BB_ERR_MSG:-"$_exception_line"}" 1>&2;
                if test -v BB_ERR_MSG; then
                    { 
                        echo -e "STACK TRACE: (TOKEN: $_exception_line)" 1>&2;
                        local -i _frame=0;
                        local _treestack='|--';
                        local _line _caller _source;
                        while read -r _line _caller _source < <(caller "$_frame"); do
                            { 
                                echo "$_treestack ${_caller} >> ${_source##*/}::${_line}" 1>&2;
                                _frame+=1;
                                _treestack+='--'
                            };
                        done
                    };
                fi
            };
        else
            { 
                echo -e "[!!!] \033[1;31merror\033[0m[$_retcode]: ${_source##*/}[$BASH_LINENO]: SUBSHELL EXITED WITH NON-ZERO STATUS" 1>&2
            };
        fi;
        return "$_retcode"
    };
    \command \unalias -a || exit;
    trap 'exit' USR1;
    trap 'BB_ERR_MSG="UNCAUGHT EXCEPTION" log::error "$BASH_COMMAND" || process::self::exit' ERR;
    set -eEuT -o pipefail;
    shopt -s inherit_errexit expand_aliases;
    ___self="$0";
    ___self_PID="$$";
    ___MAIN_FUNCNAME="main@bashbox%6559";
    ___self_NAME="multitux-gp";
    ___self_CODENAME="multitux-gp";
    ___self_AUTHORS=("AXON <axonasif@gmail.com>");
    ___self_VERSION="1.0";
    ___self_DEPENDENCIES=(std::0.1.5 argbash::0.1.0);
    ___self_REPOSITORY="https://github.com/axonasif/multitux-gp";
    ___self_BASHBOX_COMPAT="0.3.7~";
    readonly _multitux_meta_name="Bashbox.meta";
    readonly _src_dir_name="src";
    readonly _multitux_home="${HOME:-"${0%/*}"}/.multitux" && mkdir -p "$_multitux_home";
    readonly _multitux_registrydir="$_multitux_home/registry" && mkdir -p "$_multitux_registrydir";
    readonly SUBCOMMANDS_DESC=("" "Integrate a distro into your host environment" "Create Dockerfile for one of the supported distros");
    readonly _supported_distros=(archlinux centos debian fedora opensuse ubuntu voidlinux);
    readonly -A _distro_image=(["${_supported_distros[0]}"]="${_supported_distros[0]}" ["${_supported_distros[1]}"]="${_supported_distros[1]}" ["${_supported_distros[2]}"]="${_supported_distros[2]}" ["${_supported_distros[3]}"]="${_supported_distros[3]}" ["${_supported_distros[4]}"]="opensuse/leap" ["${_supported_distros[5]}"]="${_supported_distros[5]}" ["${_supported_distros[3]}"]="voidlinux/voidlinux");
    _var_exports=(_multitux_registrydir);
    for _var in "${_var_exports[@]}";
    do
        { 
            export "$_var"
        };
    done;
    function log::info () 
    { 
        echo -e "[%%%] \033[1;37minfo\033[0m: $@"
    };
    function log::warn () 
    { 
        echo -e "[***] \033[1;37mwarn\033[0m: $@"
    };
    function println::helpgen () 
    { 
        _positionals=();
        _arg_helpname=;
        _arg_short_desc=;
        _arg_usage=;
        _arg_options_desc=;
        _arg_subcommands=;
        _arg_examples=;
        _arg_footer_msg=;
        function print_help () 
        { 
            printf '%s\n' "<The general help message of my script>";
            printf 'Usage: %s [--short-desc <arg>] [--usage <arg>] [--options-desc <arg>] [--subcommands <arg>] [--examples <arg>] [--footer-msg <arg>] [-h|--help] <helpname>\n' "$0";
            printf '\t%s\n' "-h, --help: Prints help"
        };
        function parse_commandline () 
        { 
            _positionals_count=0;
            while test $# -gt 0; do
                _key="$1";
                case "$_key" in 
                    --short-desc)
                        test $# -lt 2 && println::error "Missing value for the optional argument '$_key'." 1;
                        _arg_short_desc="$2";
                        shift
                    ;;
                    --short-desc=*)
                        _arg_short_desc="${_key##--short-desc=}"
                    ;;
                    --usage)
                        test $# -lt 2 && println::error "Missing value for the optional argument '$_key'." 1;
                        _arg_usage="$2";
                        shift
                    ;;
                    --usage=*)
                        _arg_usage="${_key##--usage=}"
                    ;;
                    --options-desc)
                        test $# -lt 2 && println::error "Missing value for the optional argument '$_key'." 1;
                        _arg_options_desc="$2";
                        shift
                    ;;
                    --options-desc=*)
                        _arg_options_desc="${_key##--options-desc=}"
                    ;;
                    --subcommands)
                        test $# -lt 2 && println::error "Missing value for the optional argument '$_key'." 1;
                        _arg_subcommands="$2";
                        shift
                    ;;
                    --subcommands=*)
                        _arg_subcommands="${_key##--subcommands=}"
                    ;;
                    --examples)
                        test $# -lt 2 && println::error "Missing value for the optional argument '$_key'." 1;
                        _arg_examples="$2";
                        shift
                    ;;
                    --examples=*)
                        _arg_examples="${_key##--examples=}"
                    ;;
                    --footer-msg)
                        test $# -lt 2 && println::error "Missing value for the optional argument '$_key'." 1;
                        _arg_footer_msg="$2";
                        shift
                    ;;
                    --footer-msg=*)
                        _arg_footer_msg="${_key##--footer-msg=}"
                    ;;
                    -h | --help)
                        print_help;
                        exit 0
                    ;;
                    -h*)
                        print_help;
                        exit 0
                    ;;
                    *)
                        _last_positional="$1";
                        _positionals+=("$_last_positional");
                        _positionals_count=$((_positionals_count + 1))
                    ;;
                esac;
                shift;
            done
        };
        function handle_passed_args_count () 
        { 
            local _required_args_string="'helpname'";
            test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes println::error "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1;
            test "${_positionals_count}" -le 1 || _PRINT_HELP=yes println::error "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
        };
        function assign_positional_args () 
        { 
            local _positional_name _shift_for=$1;
            _positional_names="_arg_helpname ";
            shift "$_shift_for";
            for _positional_name in ${_positional_names};
            do
                test $# -gt 0 || break;
                eval "$_positional_name=\${1}" || println::error "Error during argument parsing." 1;
                shift;
            done
        };
        parse_commandline "$@";
        handle_passed_args_count;
        assign_positional_args 1 "${_positionals[@]}";
        echo -e "${_arg_helpname}\c";
        if test -n "$_arg_short_desc"; then
            echo -e " - $_arg_short_desc\n";
        else
            echo;
        fi;
        if test -n "$_arg_usage"; then
            echo -e "USAGE:";
            while read -r line; do
                echo -e "    $line";
            done < <(echo "$_arg_usage");
            echo;
        fi;
        for child in "$_arg_options_desc" "$_arg_subcommands";
        do
            if test -n "$child"; then
                local _startString _endString gapVar;
                _startString="$(sed 's|<^>.*||g' <<<"${child}")";
                _endString="$(sed 's|.*<^>||g' <<<"${child}")";
                mapfile -t _startString < <(echo "$_startString");
                mapfile -t _endString < <(echo "$_endString");
                local i=0;
                local firstChild=false;
                ! "$firstChild" && echo -e "OPTIONS:" || echo -e 'SUBCOMMANDS:' && firstChild=true;
                for line in "${_startString[@]}";
                do
                    gapVar="$(
					for t in $(seq $((30 - ${#line}))); do
						echo -n " "
					done
				)";
                    echo -e "    $line${gapVar}${_endString[$i]}";
                    i=$((i+1));
                done;
                echo;
            fi;
        done;
        if test -n "$_arg_examples"; then
            echo -e "EXAMPLES:";
            while read -r line; do
                echo -e "    $line";
            done < <(echo "$_arg_examples");
            echo;
        fi;
        if test -n "$_arg_footer_msg"; then
            echo -e "$_arg_footer_msg\n";
        fi
    };
    readonly RC='\033[0m' RED='\033[0;31m' BRED='\033[1;31m' GRAY='\033[1;30m';
    readonly BLUE='\033[0;34m' BBLUE='\033[1;34m' CYAN='\033[0;34m' BCYAN='\033[1;34m';
    readonly WHITE='\033[1;37m' GREEN='\033[0;32m' BGREEN='\033[1;32m' YELLOW='\033[1;33m';
    readonly PURPLE='\033[0;35m' BPURPLE='\033[1;35m' ORANGE='\033[0;33m';
    function io::file::check_newline () 
    { 
        local _input="$1";
        if ! [[ $(tail -c1 "$_input" | wc -l) -gt 0 ]]; then
            { 
                echo >> "$_input"
            };
        fi
    };
    function begins_with_short_option () 
    { 
        local first_option all_short_options='h';
        first_option="${1:0:1}";
        test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
    };
    function subcommand::compile () 
    { 
        _positionals=();
        _arg_path=;
        _arg_distro=;
        _arg_type=;
        function print_help () 
        { 
            println::helpgen "${_self_name^^}-${_subcommand_argv^^}" --short-desc "${SUBCOMMANDS_DESC[1]}" --usage "${_self_name} ${_subcommand_argv} [OPTIONAL-OPTIONS] <path>" --options-desc "-c, --distro<^>Avoid directory-as-distro
-h, --help<^>Prints this help information" --examples "### The basic way:
${YELLOW}${_self_name} ${_subcommand_argv} awesome_project${RC}

### Pre-setting project distro, avoiding directory-path as distro:
${YELLOW}${_self_name} ${_subcommand_argv} --distro cake awesome_project${RC}

### Using a specific template for project initialization(core is default):
${YELLOW}${_self_name} ${_subcommand_argv} --template kernel awesome_project${RC}

### Random usage EXAMPLES just for referrence:
${YELLOW}${_self_name} ${_subcommand_argv} --template mesa graphics_lib
${_self_name} ${_subcommand_argv} --template=kernel vanilla_kernel --distro vkernel
${_self_name} ${_subcommand_argv} --distro=cakebaker foo/bakery${RC}"
        };
        function parse_commandline () 
        { 
            _positionals_count=0;
            while test $# -gt 0; do
                _key="$1";
                case "$_key" in 
                    --distro | -c)
                        test $# -lt 2 && log::error "Missing value for the optional argument '$_key'." 1 || exit;
                        _arg_distro="$2";
                        shift
                    ;;
                    --distro=*)
                        _arg_distro="${_key##--distro=}"
                    ;;
                    --type | -t)
                        test $# -lt 2 && log::error "Missing value for the optional argument '$_key'." 1 || exit;
                        _arg_type="$2";
                        shift
                    ;;
                    --type=*)
                        _arg_type="${_key##--type=}"
                    ;;
                    -h | --help)
                        print_help;
                        exit 0
                    ;;
                    -h*)
                        print_help;
                        exit 0
                    ;;
                    *)
                        _last_positional="$1";
                        _positionals+=("$_last_positional");
                        _positionals_count=$((_positionals_count + 1))
                    ;;
                esac;
                shift;
            done
        };
        function handle_passed_args_count () 
        { 
            local _required_args_string="'path'";
            test "${_positionals_count}" -ge 1 || log::error "Not enough positional arguments " "- we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1 || exit;
            test "${_positionals_count}" -le 1 || log::error "There were spurious positional arguments ---" " we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1 || exit
        };
        function assign_positional_args () 
        { 
            local _positional_name _shift_for=$1;
            _positional_names="_arg_path ";
            shift "$_shift_for";
            for _positional_name in ${_positional_names};
            do
                test $# -gt 0 || break;
                eval "$_positional_name=\${1}" || log::error "Error during argument parsing." 1 || exit;
                shift;
            done
        };
        parse_commandline "$@";
        handle_passed_args_count;
        assign_positional_args 1 "${_positionals[@]}";
        : "${_arg_distro:="ubuntu"}";
        if test -e "$_arg_path"; then
            { 
                log::error "A dir as \`$_arg_path\` already exists." || :;
                log::info "Do you want to overwrite it? [y/N] \c";
                local _ans && read -n1 -r _ans;
                if test "${_ans,,}" == y; then
                    { 
                        rm -r "$_arg_path";
                        mkdir -p "$_arg_path"
                    };
                else
                    { 
                        exit 1
                    };
                fi
            };
        else
            { 
                mkdir -p "$_arg_path"
            };
        fi;
        if [[ ! "${_supported_distros[@]}" =~ (^| )${_arg_distro%%=*}($| ) ]]; then
            { 
                log::error "$_arg_distro is not supported" 1 || exit
            };
        fi;
        local _pkg _pkg_list;
        for _pkg in "${ALL_PACKAGES[@]}";
        do
            { 
                local -n _pkg_spec="$_pkg";
                _pkg_list+=("'${_pkg_spec[$_arg_distro]}'");
                unset _pkg_spec
            };
        done;
        function dockerfile::wrapper () 
        { 
            local _keyword="${FUNCNAME[1]}";
            local _input=("$@");
            case "$_arg_type" in 
                dockerfile)
                    case "$_keyword" in 
                        RUN)
                            printf "$_keyword ";
                            local _line;
                            while read -r _line; do
                                { 
                                    echo "${_line}"
                                };
                            done
                        ;;
                        *)
                            echo "${_keyword} ${_input[@]}"
                        ;;
                    esac
                ;;
                shellscript)
                    case "$_keyword" in 
                        ENV)
                            printf 'export %s\n' "${_input[@]}"
                        ;;
                        WORKDIR)
                            printf 'cd %s\n' "${_input[@]}"
                        ;;
                        LABEL)
                            printf '# %s\n' "${_input[@]}"
                        ;;
                        COPY)
                            true 'TODO'
                        ;;
                        USER)
                            true 'TODO'
                        ;;
                        RUN)
                            local _line;
                            while read -r _line; do
                                { 
                                    echo "${_line}"
                                };
                            done
                        ;;
                        *)
                            echo "${_input[@]}"
                        ;;
                    esac
                ;;
            esac
        };
        local _keyword;
        for _keyword in COPY ENV LABEL RUN USER WORKDIR;
        do
            { 
                eval "function ${_keyword}() { dockerfile::wrapper \"\$@\"; }"
            };
        done;
        function pkgman::perform_tasks () 
        { 
            declare -r _pkgs=("${@}");
            declare -r _div='\<#\>';
            if [[ "${_pkgs[*]}" =~ ${_div} ]]; then
                { 
                    local _pkg;
                    for _pkg in "${_pkgs[@]}";
                    do
                        { 
                            local _before="${_pkg%%${_div}*}";
                            local _name="$(
				if [[ ! "$_pkg" =~ ${_div} ]]; then {
					printf "$_pkg\n";
				} elif [[ "$_pkg" =~ ${_div}.*${_div} ]]; then {
					printf "${BASH_REMATCH//${_div}/}\n"
				} fi
			)";
                            local _after="${_pkg##*<#>}";
                            _pkg_names+=("$_name")
                        };
                    done
                };
            else
                { 
                    declare -gn _pkg_names=_pkgs
                };
            fi
        };
        function pkgman::archlinux () 
        { 
            pkgman::perform_tasks "${@}";
            pacman -Syyu --noconfirm --noprogressbar --needed "${_pkg_names[@]}";
            pacman -Scc --noconfirm
        };
        { 
            printf 'FROM %s:latest\n' "${_distro_image[$_arg_distro]}";
            ENV LANG=en_US.UTF-8;
            COPY install-packages /usr/bin/;
            printf '%s\n' "$(builtin declare -f 'pkgman::perform_tasks')" "$(builtin declare -f "pkgman::$_arg_distro")" "pkgman::$_arg_distro \"\$@\"" > "$_arg_path/install-packages";
            RUN <<EOF
install-packages ${_pkg_list[@]} 	&& useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod     	&& sed -i.bak -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers 	&& printf '%s\n' "PS1='\[]0;\u \w\]\[[01;32m\]\u\[[00m\] \[[01;34m\]\w\[[00m\] \$ '" 		'source "\$HOME/.bashrc.d"/*' | sudo -u gitpod tee -a "/home/gitpod/.bashrc" 	&& sudo -u gitpod mkdir -m0755 -p /home/gitpod/.bashrc.d
EOF

            ENV HOME=/home/gitpod;
            WORKDIR \$HOME
        } > "$_arg_path/Dockerfile"
    };
    function declare () 
    { 
        local args=("$@");
        local _pkg="${args[1]}";
        local -n _group="${GROUP^^}_GROUP" && _group+=("${_pkg}");
        ALL_PACKAGES+=("${_pkg}");
        builtin declare "$@"
    };
    local GROUP="base";
    declare -A bash=([archlinux]="bash" [centos]="bash" [fedora]="bash" [opensuse]="bash" [ubuntu]="bash" [voidlinux]="bash");
    declare -A curl=([archlinux]="curl" [centos]="curl" [debian]="curl" [fedora]="curl" [opensuse]="curl" [ubuntu]="curl" [voidlinux]="curl");
    declare -A ca__certificates=([archlinux]="ca-certificates" [centos]="ca-certificates" [debian]="ca-certificates" [fedora]="ca-certificates" [opensuse]="ca-certificates" [ubuntu]="ca-certificates" [voidlinux]="ca-certificates");
    declare -A netbase=([archlinux]="" [centos]="" [debian]="netbase" [fedora]="" [opensuse]="" [ubuntu]="netbase" [voidlinux]="iptables");
    declare -A wget=([archlinux]="wget" [centos]="wget" [debian]="wget" [fedora]="wget" [opensuse]="wget" [ubuntu]="wget" [voidlinux]="wget");
    declare -A tzdata=([archlinux]="tzdata" [centos]="tzdata" [debian]="tzdata" [fedora]="tzdata" [opensuse]="timezone" [ubuntu]="tzdata" [voidlinux]="tzdata");
    declare -A gnupg=([archlinux]="gnupg" [centos]="gnupg" [debian]="gnupg" [fedora]="gnupg" [opensuse]="gpg2" [ubuntu]="gnupg" [voidlinux]="gnupg");
    declare -A openssh_client=([archlinux]="openssh" [centos]="openssh" [debian]="openssh-client" [fedora]="openssh" [opensuse]="openssh" [ubuntu]="openssh-client" [voidlinux]="openssh");
    declare -A procps=([archlinux]="procps-ng" [centos]="procps-ng" [debian]="procps" [fedora]="procps-ng" [opensuse]="procps" [ubuntu]="procps" [voidlinux]="procps-ng");
    declare -A bzip2=([archlinux]="bzip2" [centos]="bzip2" [debian]="bzip2" [fedora]="bzip2" [opensuse]="bzip2" [ubuntu]="bzip2" [voidlinux]="bzip2");
    declare -A file=([archlinux]="file" [centos]="file" [debian]="file" [fedora]="file" [opensuse]="file" [ubuntu]="file" [voidlinux]="file");
    declare -A unzip=([archlinux]="unzip" [centos]="unzip" [debian]="unzip" [fedora]="unzip" [opensuse]="unzip" [ubuntu]="unzip" [voidlinux]="unzip");
    declare -A zip=([archlinux]="zip" [centos]="zip" [debian]="zip" [fedora]="zip" [opensuse]="zip" [ubuntu]="zip" [voidlinux]="zip");
    declare -A bash__completion=([archlinux]="bash-completion" [centos]="bash-completion" [debian]="bash-completion" [fedora]="bash-completion" [opensuse]="bash-completion" [ubuntu]="bash-completion" [voidlinux]="bash-completion");
    declare -A htop=([archlinux]="htop" [centos]="htop" [debian]="htop" [fedora]="htop" [opensuse]="htop" [ubuntu]="htop" [voidlinux]="htop");
    declare -A less=([archlinux]="less" [centos]="less" [debian]="less" [fedora]="less" [opensuse]="less" [ubuntu]="less" [voidlinux]="less");
    declare -A locales=([archlinux]="" [centos]="" [debian]="locales" [fedora]="" [opensuse]="" [ubuntu]="locales" [voidlinux]="");
    declare -A man__db=([archlinux]="man-db" [centos]="man-db" [debian]="man-db" [fedora]="man-db" [opensuse]="man" [ubuntu]="man-db" [voidlinux]="man-db");
    declare -A nano=([archlinux]="nano" [centos]="nano" [debian]="nano" [fedora]="nano" [opensuse]="nano" [ubuntu]="nano" [voidlinux]="nano");
    declare -A ripgrep=([archlinux]="ripgrep" [centos]="dnf config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/repo/epel-7/carlwgeorge-ripgrep-epel-7.repo||ripgrep" [debian]="ripgrep" [fedora]="ripgrep" [opensuse]="ripgrep" [ubuntu]="ripgrep" [voidlinux]="ripgrep");
    declare -A software__properties__common=([archlinux]="" [centos]="" [debian]="software-properties-common" [fedora]="" [opensuse]="" [ubuntu]="software-properties-common" [voidlinux]="");
    declare -A sudo=([archlinux]="sudo" [centos]="sudo" [debian]="sudo" [fedora]="sudo" [opensuse]="sudo" [ubuntu]="sudo" [voidlinux]="sudo");
    declare -A time=([archlinux]="time" [centos]="time" [debian]="time" [fedora]="time" [opensuse]="time" [ubuntu]="time" [voidlinux]="time");
    declare -A emacs__nox=([archlinux]="emacs-nox" [centos]="emacs-nox" [debian]="emacs-nox" [fedora]="emacs-nox" [opensuse]="emacs-nox" [ubuntu]="emacs-nox" [voidlinux]="emacs");
    declare -A vim=([archlinux]="vim" [centos]="vim-enhanced" [debian]="vim" [fedora]="vim-enhanced" [opensuse]="vim" [ubuntu]="vim" [voidlinux]="vim");
    declare -A multitail=([archlinux]="multitail" [centos]="multitail" [debian]="multitail" [fedora]="multitail" [opensuse]="multitail" [ubuntu]="multitail" [voidlinux]="multitail");
    declare -A lsof=([archlinux]="lsof" [centos]="lsof" [debian]="lsof" [fedora]="lsof" [opensuse]="lsof" [ubuntu]="lsof" [voidlinux]="lsof");
    declare -A ssl__cert=([archlinux]="" [centos]="" [debian]="ssl-cert" [fedora]="" [opensuse]="" [ubuntu]="ssl-cert" [voidlinux]="");
    declare -A fish=([archlinux]="fish" [centos]="fish" [debian]="fish" [fedora]="fish" [opensuse]="fish" [ubuntu]="fish" [voidlinux]="fish-shell");
    declare -A zsh=([archlinux]="zsh" [centos]="zsh" [debian]="zsh" [fedora]="zsh" [opensuse]="zsh" [ubuntu]="zsh" [voidlinux]="zsh");
    declare -A patch=([archlinux]="patch" [centos]="patch" [debian]="patch" [fedora]="patch" [opensuse]="patch" [ubuntu]="patch" [voidlinux]="patch");
    declare -A xz_utils=([archlinux]="xz" [centos]="xz" [debian]="xz-utils" [fedora]="xz" [opensuse]="xz" [ubuntu]="xz-utils" [voidlinux]="xz");
    unset GROUP;
    local GROUP="tools";
    declare -A dirmngr=([archlinux]="gnupg" [centos]="gnupg2" [debian]="dirmngr" [fedora]="gnupg2" [opensuse]="dirmngr" [ubuntu]="dirmngr" [voidlinux]="gnupg");
    declare -A bzr=([archlinux]="yay -Sy bzr||" [centos]="" [debian]="bzr" [fedora]="" [opensuse]="bzr" [ubuntu]="bzr" [voidlinux]="bzr");
    declare -A git=([archlinux]="git" [centos]="git" [debian]="git" [fedora]="git" [opensuse]="git" [ubuntu]="git" [voidlinux]="git");
    declare -A git_lfs=([archlinux]="git-lfs" [centos]="git-lfs" [debian]="git-lfs" [fedora]="git-lfs" [opensuse]="git-lfs" [ubuntu]="git-lfs" [voidlinux]="git-lfs");
    declare -A mercurial=([archlinux]="mercurial" [centos]="mercurial" [debian]="mercurial" [fedora]="mercurial" [opensuse]="mercurial" [ubuntu]="mercurial" [voidlinux]="mercurial");
    declare -A subversion=([archlinux]="subversion" [centos]="subversion" [debian]="subversion" [fedora]="subversion" [opensuse]="subversion" [ubuntu]="subversion" [voidlinux]="subversion");
    declare -A jq=([archlinux]="jq" [centos]="jq" [debian]="jq" [fedora]="jq" [opensuse]="jq" [ubuntu]="jq" [voidlinux]="jq");
    unset GROUP;
    local GROUP="c_cpp_base";
    declare -A autoconf=([archlinux]="autoconf" [centos]="autoconf" [debian]="autoconf" [fedora]="autoconf" [opensuse]="autoconf" [ubuntu]="autoconf" [voidlinux]="autoconf");
    declare -A automake=([archlinux]="automake" [centos]="automake" [debian]="automake" [fedora]="automake" [opensuse]="automake" [ubuntu]="automake" [voidlinux]="automake");
    declare -A make=([archlinux]="make" [centos]="make" [debian]="make" [fedora]="make" [opensuse]="make" [ubuntu]="make" [voidlinux]="make");
    declare -A libtool=([archlinux]="libtool" [centos]="libtool" [debian]="libtool" [fedora]="libtool" [opensuse]="libtool" [ubuntu]="libtool" [voidlinux]="libtool");
    declare -A g_plus_plus=([archlinux]="g++" [centos]="g++" [debian]="g++" [fedora]="g++" [opensuse]="g++" [ubuntu]="g++" [voidlinux]="g++");
    declare -A gcc=([archlinux]="gcc" [centos]="gcc" [debian]="gcc" [fedora]="gcc" [opensuse]="gcc" [ubuntu]="gcc" [voidlinux]="gcc");
    declare -A ninja_build=([archlinux]="ninja" [centos]="ninja-build" [debian]="ninja-build" [fedora]="ninja-build" [opensuse]="ninja" [ubuntu]="ninja-build" [voidlinux]="ninja");
    local GROUP="c_cpp_headers";
    declare -A libbz2_dev=([archlinux]="" [centos]="bzip2-devel-1.0.8-9.fc35.i686" [debian]="libbz2-dev" [fedora]="bzip2-devel-1.0.8-9.fc35.i686" [opensuse]="" [ubuntu]="libbz2-dev" [voidlinux]="bzip2-devel");
    unset GROUP;
    local GROUP="EXTRAS";
    declare -A build_essential=([archlinux]="base-devel" [centos]='dnf groupinstall -y "Development Tools"||' [debian]="build-essential" [fedora]='dnf groupinstall -y "Development Tools"||' [opensuse]='zypper install -y -t pattern devel_basis||' [ubuntu]="build-essential" [voidlinux]="base-devel");
    declare -A dpkg_dev=([archlinux]="" [centos]="" [debian]="dpkg-dev" [fedora]="" [opensuse]="" [ubuntu]="dpkg-dev" [voidlinux]="");
    declare -A imagemagick=([archlinux]="imagemagick" [centos]="imagemagick" [debian]="imagemagick" [fedora]="imagemagick" [opensuse]="imagemagick" [ubuntu]="imagemagick" [voidlinux]="imagemagick");
    unset GROUP;
    unset -f declare;
    function print_help () 
    { 
        println::helpgen "${_self_name^^}" --short-desc "Run multiple linux distros in Gitpod" --usage "${_self_name} [OPTIONAL-OPTIONS] [SUBCOMMAND] <subcommand-arguments>" --options-desc "-V, --version<^>Print version info and exit
-v, --verbose<^>Use very verbose output
-q, --quiet<^>No output printed to stdout
-h, --help<^>Prints this help information" --subcommands "parallel<^>${SUBCOMMANDS_DESC[1]}
compile<^>${SUBCOMMANDS_DESC[2]}
" --footer-msg "Try '${_self_name} <subcommand> --help' for more information on a specific command.
For bugreports: $___self_REPOSITORY"
    };
    function main () 
    { 
        _self_name="${___self##*/}";
        _arg_verbose=off;
        _arg_quiet=off;
        for _arg in "${@}";
        do
            { 
                if test "$_arg" != "--" && grep -E '\-\w+' <<< "$_arg" > /dev/null; then
                    { 
                        case "$_arg" in 
                            --verbose | -v)
                                _arg_verbose=on
                            ;;
                            --quiet | -q)
                                _arg_quiet=on
                            ;;
                            --version | -V)
                                echo "$___self_VERSION";
                                exit 0
                            ;;
                            --help | -h*)
                                print_help && exit 0
                            ;;
                        esac;
                        shift
                    };
                else
                    { 
                        break
                    };
                fi
            };
        done;
        unset _arg;
        _subcommand_argv="${1:-}" && shift || true;
        case "$_subcommand_argv" in 
            parallel | compile)
                subcommand::$_subcommand_argv "$@"
            ;;
            *)
                test -n "$_subcommand_argv" && log::warn "Unknown subcommand: $_subcommand_argv";
                print_help;
                test -n "$_subcommand_argv" && exit 1 || exit 0
            ;;
        esac;
        exit
    };
    main "$@";
    wait;
    exit
}
main@bashbox%6559 "$@";
